name: privacy_of_animal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.20.0
  firebase_auth: ^0.6.6
  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.8.2+1
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  flutter_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

    - assets/images/animals/bison.jpg
    - assets/images/animals/buffalo.jpg
    - assets/images/animals/camel.jpg
    - assets/images/animals/cat.jpg
    - assets/images/animals/cheetah.jpg
    - assets/images/animals/crocodile.jpg
    - assets/images/animals/deer.jpg
    - assets/images/animals/dog.jpg
    - assets/images/animals/dolphin.jpg
    - assets/images/animals/duck.jpg
    - assets/images/animals/eagle.jpg
    - assets/images/animals/elephant.jpg
    - assets/images/animals/fox.jpg
    - assets/images/animals/goat.jpg
    - assets/images/animals/gorilla.jpg
    - assets/images/animals/hippo.jpg
    - assets/images/animals/horse.jpg
    - assets/images/animals/koala.jpg
    - assets/images/animals/lama.jpg
    - assets/images/animals/lion.jpg
    - assets/images/animals/monkey.jpg
    - assets/images/animals/owl.jpg
    - assets/images/animals/parrot.jpg
    - assets/images/animals/penguin.jpg
    - assets/images/animals/pig.jpg
    - assets/images/animals/rabbit.jpg
    - assets/images/animals/rhinoceros.jpg
    - assets/images/animals/seal.jpg
    - assets/images/animals/shark.jpg
    - assets/images/animals/sheep.jpg
    - assets/images/animals/snake.jpg
    - assets/images/animals/tiger.jpg
    - assets/images/animals/turtle.jpg
    - assets/images/animals/whale.jpg
    - assets/images/animals/zebra.jpg


  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 500
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 900
